import type { Product } from "./types"

export const themes = {
  "summer-vibes": {
    id: "summer-vibes",
    title: "Summer Vibes",
    description: "Create the perfect summer outfit with bright colors and light fabrics",
    budget: 5000,
    rules: ["Must include bright colors", "Light, breathable fabrics only", "Summer accessories encouraged"],
  },
  "office-chic": {
    id: "office-chic",
    title: "Office Chic",
    description: "Professional yet stylish - perfect for the modern workplace",
    budget: 8000,
    rules: ["Professional appearance", "Neutral or muted colors", "Business appropriate"],
  },
  "festival-ready": {
    id: "festival-ready",
    title: "Festival Ready",
    description: "Traditional meets contemporary for the festive season",
    budget: 12000,
    rules: ["Traditional elements required", "Festive colors encouraged", "Cultural appropriateness"],
  },
  "casual-weekend": {
    id: "casual-weekend",
    title: "Casual Weekend",
    description: "Comfortable yet stylish for weekend adventures",
    budget: 4000,
    rules: ["Comfort is key", "Versatile pieces", "Mix and match friendly"],
  },
  "date-night": {
    id: "date-night",
    title: "Date Night",
    description: "Romantic and elegant for special evenings",
    budget: 7000,
    rules: ["Elegant silhouettes", "Romantic colors", "Statement accessories"],
  },
}

export const products: Product[] = [
  // Summer Vibes Products
  {
    id: "clothing-dresses-summer-1",
    name: "Floral Maxi Dress",
    brand: "Zara",
    price: 2999,
    image: "/floral-summer-dress.png",
    category: "clothing",
    subcategory: "Dresses",
    colors: ["Yellow", "Pink", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["summer", "floral", "maxi"],
    themes: ["summer-vibes", "casual-weekend"],
  },
  {
    id: "clothing-dresses-summer-2",
    name: "Bright Sundress",
    brand: "H&M",
    price: 1899,
    image: "/bright-sundress.png",
    category: "clothing",
    subcategory: "Dresses",
    colors: ["Orange", "Coral", "Turquoise"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["summer", "bright", "casual"],
    themes: ["summer-vibes"],
  },
  {
    id: "clothing-tops-summer-1",
    name: "Crop Top",
    brand: "Forever 21",
    price: 899,
    image: "/crop-top.png",
    category: "clothing",
    subcategory: "Tops",
    colors: ["White", "Yellow", "Pink"],
    sizes: ["XS", "S", "M", "L"],
    tags: ["summer", "crop", "trendy"],
    themes: ["summer-vibes", "casual-weekend"],
  },
  {
    id: "shoes-sandals-summer-1",
    name: "Strappy Sandals",
    brand: "Steve Madden",
    price: 1599,
    image: "/strappy-sandals.png",
    category: "shoes",
    subcategory: "Sandals",
    colors: ["Tan", "White", "Black"],
    sizes: ["6", "7", "8", "9", "10"],
    tags: ["summer", "strappy", "casual"],
    themes: ["summer-vibes", "casual-weekend"],
  },
  {
    id: "accessories-earrings-summer-1",
    name: "Hoop Earrings",
    brand: "Accessorize",
    price: 599,
    image: "/gold-hoop-earrings.png",
    category: "accessories",
    subcategory: "Earrings",
    colors: ["Gold", "Silver"],
    sizes: ["One Size"],
    tags: ["hoops", "versatile"],
    themes: ["summer-vibes", "casual-weekend", "date-night"],
  },

  // Office Chic Products
  {
    id: "clothing-blazers-office-1",
    name: "Navy Blazer",
    brand: "Mango",
    price: 3499,
    image: "/navy-blazer.png",
    category: "clothing",
    subcategory: "Blazers",
    colors: ["Navy", "Black", "Grey"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["professional", "blazer", "formal"],
    themes: ["office-chic"],
  },
  {
    id: "clothing-shirts-office-1",
    name: "White Button Shirt",
    brand: "Uniqlo",
    price: 1999,
    image: "/white-button-shirt.png",
    category: "clothing",
    subcategory: "Shirts",
    colors: ["White", "Light Blue", "Cream"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["professional", "classic", "versatile"],
    themes: ["office-chic"],
  },
  {
    id: "clothing-trousers-office-1",
    name: "Formal Trousers",
    brand: "Marks & Spencer",
    price: 2299,
    image: "/formal-trousers.png",
    category: "clothing",
    subcategory: "Trousers",
    colors: ["Black", "Navy", "Grey"],
    sizes: ["28", "30", "32", "34", "36"],
    tags: ["professional", "formal", "tailored"],
    themes: ["office-chic"],
  },
  {
    id: "shoes-heels-office-1",
    name: "Block Heels",
    brand: "Clarks",
    price: 2799,
    image: "/block-heels.png",
    category: "shoes",
    subcategory: "Heels",
    colors: ["Black", "Nude", "Brown"],
    sizes: ["6", "7", "8", "9", "10"],
    tags: ["professional", "comfortable", "block-heel"],
    themes: ["office-chic", "date-night"],
  },

  // Festival Ready Products
  {
    id: "clothing-kurtas-festival-1",
    name: "Embroidered Kurta",
    brand: "Fabindia",
    price: 4999,
    image: "/embroidered-kurta.png",
    category: "clothing",
    subcategory: "Kurtas",
    colors: ["Royal Blue", "Maroon", "Gold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["traditional", "embroidered", "festive"],
    themes: ["festival-ready"],
  },
  {
    id: "clothing-lehengas-festival-1",
    name: "Designer Lehenga",
    brand: "Sabyasachi",
    price: 8999,
    image: "/designer-lehenga.png",
    category: "clothing",
    subcategory: "Lehengas",
    colors: ["Red", "Pink", "Green"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["traditional", "designer", "wedding"],
    themes: ["festival-ready"],
  },
  {
    id: "accessories-jewelry-festival-1",
    name: "Statement Necklace",
    brand: "Tanishq",
    price: 2999,
    image: "/statement-necklace.png",
    category: "accessories",
    subcategory: "Necklaces",
    colors: ["Gold", "Silver"],
    sizes: ["One Size"],
    tags: ["traditional", "statement", "jewelry"],
    themes: ["festival-ready", "date-night"],
  },

  // Additional products for variety
  {
    id: "clothing-jeans-casual-1",
    name: "High-Waist Jeans",
    brand: "Levi's",
    price: 2499,
    image: "/high-waist-jeans.png",
    category: "clothing",
    subcategory: "Jeans",
    colors: ["Blue", "Black", "White"],
    sizes: ["26", "28", "30", "32", "34"],
    tags: ["casual", "denim", "high-waist"],
    themes: ["casual-weekend"],
  },
  {
    id: "shoes-sneakers-casual-1",
    name: "White Sneakers",
    brand: "Adidas",
    price: 3999,
    image: "/white-sneakers.png",
    category: "shoes",
    subcategory: "Sneakers",
    colors: ["White", "Black", "Grey"],
    sizes: ["6", "7", "8", "9", "10"],
    tags: ["casual", "comfortable", "sporty"],
    themes: ["casual-weekend"],
  },
  {
    id: "accessories-bags-1",
    name: "Crossbody Bag",
    brand: "Coach",
    price: 4999,
    image: "/crossbody-bag.png",
    category: "accessories",
    subcategory: "Bags",
    colors: ["Brown", "Black", "Tan"],
    sizes: ["One Size"],
    tags: ["versatile", "crossbody", "leather"],
    themes: ["office-chic", "casual-weekend", "date-night"],
  },
  {
    id: "addons-perfume-1",
    name: "Floral Perfume",
    brand: "Chanel",
    price: 3999,
    image: "/floral-perfume.png",
    category: "addons",
    subcategory: "Perfumes",
    colors: ["Clear"],
    sizes: ["50ml", "100ml"],
    tags: ["floral", "luxury", "fragrance"],
    themes: ["summer-vibes", "date-night", "festival-ready"],
  },
]

export function getProductsByThemeAndCategory(themeId: string, category: string, subcategory?: string): Product[] {
  return products.filter((product) => {
    const matchesTheme = product.themes?.includes(themeId) || false
    const matchesCategory = product.category === category
    const matchesSubcategory = !subcategory || product.subcategory === subcategory

    return matchesTheme && matchesCategory && matchesSubcategory
  })
}

export function getTheme(themeId: string) {
  return themes[themeId as keyof typeof themes]
}
